-- Gerado por scripts/importar_dpen.py a partir da planilha "DPEN 25-26.xlsx" (Heitor, 08/10/2026).
-- Insumos, fornecedores e fichas de eventos. Ponto de partida: tudo pode ser corrigido pela tela (cria versão nova).
select set_config('portal.origem_preco', 'planilha DPEN', true);

insert into fornecedores (nome) values
  ('24 print'),
  ('Ap 42'),
  ('Assai'),
  ('Avícola Dalmas'),
  ('Cabana'),
  ('City pães'),
  ('Coca'),
  ('Cold Smoke'),
  ('Contato Henrique'),
  ('Di Calani'),
  ('Espaço Gastronomico'),
  ('FC Cups'),
  ('Flavour House'),
  ('Food center'),
  ('Hortifruti'),
  ('Internet'),
  ('Irmãos Avelino'),
  ('Ki Morango'),
  ('Loja Santo Antônio'),
  ('McCoy'),
  ('Mercado Livre'),
  ('Mercadão da Lapa'),
  ('Mercadão da Lapa ou fornecedor'),
  ('Nakao'),
  ('Pety Fritas'),
  ('PMG'),
  ('PMG ou Assai'),
  ('RC Ovos'),
  ('Rei dos Temperos');

insert into insumos (nome, categoria, unidade, embalagem, preco, fornecedor_id, observacao, ativo) values
  ('Água', 'Bebidas', 'un', 'fardo', 1.5, null, null, true),
  ('Água com gás', 'Bebidas', 'un', null, 1.5, null, null, true),
  ('Azeite', 'Óleos / Gorduras', 'kg', null, 61.7, null, null, true),
  ('Bacon', 'Embutidos / Frios', 'kg', null, 25.99, (select id from fornecedores where lower(nome) = lower('PMG')), null, true),
  ('Calabresa fatiada Pizza', 'Embutidos / Frios', 'un', null, 37.98, (select id from fornecedores where lower(nome) = lower('PMG ou Assai')), null, true),
  ('Catupiry', 'Laticínios / Queijos', 'kg', null, 38.9933, (select id from fornecedores where lower(nome) = lower('PMG')), null, true),
  ('Cebola Roxa', 'Hortifruti', 'kg', null, 7.22, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Cenoura', 'Hortifruti', 'kg', null, 9.6, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, true),
  ('Cestinha Focaccia Evento', 'Massas / Pães', 'un', null, 0.52, (select id from fornecedores where lower(nome) = lower('24 print')), null, true),
  ('Coca-Cola', 'Bebidas', 'un', 'fardo', 3.39, (select id from fornecedores where lower(nome) = lower('Coca')), null, true),
  ('Coca-Zero', 'Bebidas', 'un', 'fardo', 3.39, (select id from fornecedores where lower(nome) = lower('Coca')), null, true),
  ('Cogumelo paris', 'Hortifruti', 'kg', null, 18.0, (select id from fornecedores where lower(nome) = lower('Nakao')), null, true),
  ('Copa Lombo', 'Embutidos / Frios', 'kg', null, 98.0, (select id from fornecedores where lower(nome) = lower('Di Calani')), null, true),
  ('Creme De Leite 0.2Ml', 'Laticínios', 'kg', null, 2.55, (select id from fornecedores where lower(nome) = lower('PMG')), null, true),
  ('Creme de Ovomaltine 900g', 'Confeitaria / Sobremesas', 'kg', null, 51.99, (select id from fornecedores where lower(nome) = lower('Loja Santo Antônio')), null, true),
  ('Farinha de Trigo Italiana', 'Mercearia / Secos', 'kg', null, 12.55, (select id from fornecedores where lower(nome) = lower('Espaço Gastronomico')), null, true),
  ('Farinha Sêmola', 'Mercearia / Secos', 'kg', null, 8.56, (select id from fornecedores where lower(nome) = lower('Espaço Gastronomico')), null, true),
  ('Fermento Biológico', 'Mercearia / Secos', 'kg', null, 9.16, (select id from fornecedores where lower(nome) = lower('Irmãos Avelino')), null, true),
  ('Focaccia Forma', 'Massas / Pães', 'un', null, 30.0, (select id from fornecedores where lower(nome) = lower('Ap 42')), null, true),
  ('Gema Pasteurizada', 'Ovos / Derivados', 'un', null, 41.6, (select id from fornecedores where lower(nome) = lower('RC Ovos')), null, false),
  ('Gorgonzola', 'Laticínios / Queijos', 'kg', null, 51.98, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Guaraná', 'Bebidas', 'un', 'fardo', 2.99, (select id from fornecedores where lower(nome) = lower('Food center')), null, true),
  ('Guaraná Zero', 'Bebidas', 'un', 'fardo', 2.8912, (select id from fornecedores where lower(nome) = lower('Food center')), null, true),
  ('Manjericão', 'Hortifruti', 'kg', null, 7.5, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, true),
  ('Marshmallow', 'Confeitaria / Sobremesas', 'un', null, 30.0, (select id from fornecedores where lower(nome) = lower('Loja Santo Antônio')), null, false),
  ('Missô', 'Molhos / Condimentos', 'kg', null, 24.38, (select id from fornecedores where lower(nome) = lower('Irmãos Avelino')), null, true),
  ('Molho Tomate Italiano Lata 2.55kg', 'Molhos / Condimentos', 'kg', null, 14.4745, (select id from fornecedores where lower(nome) = lower('Irmãos Avelino')), null, true),
  ('Mortadela', 'Embutidos / Frios', 'un', null, 14.97, (select id from fornecedores where lower(nome) = lower('Mercadão da Lapa ou fornecedor')), null, true),
  ('Mostarda Anciene', 'Molhos / Condimentos', 'kg', 'pote', 119.8667, (select id from fornecedores where lower(nome) = lower('Mercadão da Lapa')), 'Na planilha a unidade de compra é "pote"; conferir se o preço é por kg.', true),
  ('Mostarda Galão Cepera 3.3kg', 'Molhos / Condimentos', 'kg', null, 8.1515, (select id from fornecedores where lower(nome) = lower('PMG')), null, true),
  ('Mussarela', 'Laticínios / Queijos', 'kg', null, 39.88, (select id from fornecedores where lower(nome) = lower('PMG')), null, true),
  ('Mussarela de Bufala', 'Laticínios / Queijos', 'kg', null, 70.0, null, null, true),
  ('Óleo de Soja', 'Óleos / Gorduras', 'un', 'fardo', 7.9389, null, null, true),
  ('Parmesão ralado pacote', 'Laticínios / Queijos', 'kg', null, 80.0, (select id from fornecedores where lower(nome) = lower('Di Calani')), null, true),
  ('Pastrami', 'Embutidos / Frios', 'kg', null, 76.0, (select id from fornecedores where lower(nome) = lower('Cold Smoke')), null, true),
  ('Peito de Frango', 'Carnes / Proteínas', 'kg', null, 13.69, (select id from fornecedores where lower(nome) = lower('Food center')), null, true),
  ('Pety Fritas', 'Batatas / Congelados', 'un', null, 15.5, (select id from fornecedores where lower(nome) = lower('Pety Fritas')), null, true),
  ('Picles Burgers', 'Conservas', 'kg', null, 20.7221, (select id from fornecedores where lower(nome) = lower('McCoy')), null, true),
  ('Pimenta do Reino', 'Temperos / Condimentos', 'un', null, 76.1648, (select id from fornecedores where lower(nome) = lower('Rei dos Temperos')), null, true),
  ('Pistache sem casca cru', 'Castanhas / Oleaginosas', 'kg', null, 190.0, (select id from fornecedores where lower(nome) = lower('Mercadão da Lapa')), null, true),
  ('Pratinho pizza evento', 'Embalagens / Descartáveis', 'un', null, 0.545, (select id from fornecedores where lower(nome) = lower('Mercado Livre')), null, true),
  ('Presunto parma 80g', 'Embutidos / Frios', 'kg', null, 140.0, (select id from fornecedores where lower(nome) = lower('Irmãos Avelino')), null, true),
  ('Queijo Minas', 'Laticínios / Queijos', 'kg', null, 44.97, (select id from fornecedores where lower(nome) = lower('PMG ou Assai')), null, true),
  ('Redução de Balsâmico', 'Molhos / Condimentos', 'un', null, 100.0, (select id from fornecedores where lower(nome) = lower('Irmãos Avelino')), null, true),
  ('Repolho Roxo', 'Hortifruti', 'un', null, 11.33, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, true),
  ('Repolho verde', 'Hortifruti', 'un', null, 8.5, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, true),
  ('Rúcula', 'Hortifruti', 'un', null, 6.4, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, true),
  ('Sal Refinado', 'Temperos / Condimentos', 'kg', null, 2.17, null, null, true),
  ('Shimeji', 'Hortifruti', 'kg', null, 20.0, (select id from fornecedores where lower(nome) = lower('Nakao')), null, true),
  ('Xerem de castanha de Caju', 'Castanhas / Oleaginosas', 'kg', null, 37.63, (select id from fornecedores where lower(nome) = lower('Mercadão da Lapa')), null, true),
  ('Abobrinha grelhada', 'Preparos / Semiprontos', 'kg', null, 8.32, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Açúcar Refinado', 'Mercearia / Secos', 'kg', null, 2.99, null, null, false),
  ('Alho', 'Hortifruti', 'un', null, 30.0, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Alho em pó', 'Temperos / Condimentos', 'un', null, 30.0, (select id from fornecedores where lower(nome) = lower('Rei dos Temperos')), null, false),
  ('Alho frito', 'Temperos / Condimentos', 'un', null, 8.36, (select id from fornecedores where lower(nome) = lower('Rei dos Temperos')), null, false),
  ('Batata inglesa', 'Hortifruti', 'kg', null, 8.96, null, null, false),
  ('Batata palha', 'Mercearia / Secos', 'kg', null, 31.125, null, null, false),
  ('Blend burger 1 unidade (100g)', 'Carnes / Proteínas', 'un', null, 33.0, (select id from fornecedores where lower(nome) = lower('Cabana')), null, false),
  ('Bolacha Maizena', 'Mercearia / Secos', 'kg', null, 13.0497, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Burrata', 'Laticínios / Queijos', 'un', null, null, (select id from fornecedores where lower(nome) = lower('Assai')), null, false),
  ('Carne de Lagarto', 'Carnes / Proteínas', 'kg', null, 31.79, (select id from fornecedores where lower(nome) = lower('Food center')), null, false),
  ('Carne Louca', 'Preparos / Semiprontos', 'kg', null, null, null, 'Produção própria, sem ficha na planilha.', false),
  ('Cebola', 'Hortifruti', 'kg', null, 6.37, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Cebolinha', 'Hortifruti', 'un', null, 16.9, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Chá Gelado Gengibre', 'Bebidas', 'kg', null, null, null, 'Produção própria, sem ficha na planilha.', false),
  ('Chocolate Cobertura Top', 'Confeitaria / Sobremesas', 'kg', null, 29.7166, (select id from fornecedores where lower(nome) = lower('Loja Santo Antônio')), null, false),
  ('Chocolate em pó 100%', 'Confeitaria / Sobremesas', 'kg', null, null, (select id from fornecedores where lower(nome) = lower('Loja Santo Antônio')), null, false),
  ('Chocolate meio amargo', 'Confeitaria / Sobremesas', 'kg', null, 82.7201, (select id from fornecedores where lower(nome) = lower('Loja Santo Antônio')), null, false),
  ('Cream Cheese', 'Laticínios / Queijos', 'kg', null, 22.66, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Extrato de tomate', 'Molhos / Condimentos', 'un', null, 20.0, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Farinha de Trigo', 'Mercearia / Secos', 'un', null, 31.86, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Farinha Panko', 'Mercearia / Secos', 'un', null, 11.6558, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Farofa de brownie', 'Confeitaria / Sobremesas', 'un', null, 8.6, null, 'Produção própria, sem ficha na planilha.', false),
  ('Fatia Cheesecake Pistache', 'Confeitaria / Sobremesas', 'un', null, null, null, 'Produção própria, sem ficha na planilha.', false),
  ('Fermento Químico', 'Mercearia / Secos', 'kg', null, 53.24, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Fettuccine', 'Massas / Pães', 'un', null, 15.0, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Frutas vermelhas congeladas', 'Frutas / Congelados', 'kg', null, 40.44, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Ganache de pistache', 'Confeitaria / Sobremesas', 'kg', 'balde', 330.5, (select id from fornecedores where lower(nome) = lower('Espaço Gastronomico')), 'Na planilha a unidade de compra é "baldes"; conferir se o preço é por kg.', false),
  ('Gengibre', 'Hortifruti', 'kg', null, null, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Iogurte', 'Laticínios', 'un', null, 10.0, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Kafta de Cordeiro', 'Carnes / Proteínas', 'un', null, 77.2771, (select id from fornecedores where lower(nome) = lower('Contato Henrique')), null, false),
  ('Leite Integral', 'Laticínios', 'kg', null, 5.4617, null, null, false),
  ('Limão Tahiti', 'Hortifruti', 'kg', null, 3.11, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Maionese verde', 'Preparos / Molhos', 'kg', null, 0.2797, null, 'Produção própria, sem ficha na planilha.', false),
  ('Manteiga sem sal', 'Laticínios / Gorduras', 'kg', null, 47.972, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Mel', 'Mercearia / Secos', 'un', null, 46.98, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Milho verde', 'Hortifruti / Conservas', 'kg', null, 16.5941, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Molho de tahine apimentado', 'Molhos / Condimentos', 'un', null, null, (select id from fornecedores where lower(nome) = lower('Irmãos Avelino')), null, false),
  ('Molho de tomate', 'Molhos / Condimentos', 'un', null, null, null, 'Produção própria, sem ficha na planilha.', false),
  ('Morango', 'Hortifruti', 'kg', 'caixa', 6.25, (select id from fornecedores where lower(nome) = lower('Ki Morango')), 'Na planilha a unidade de compra é "cx"; conferir se o preço é por kg.', false),
  ('Noz Moscada', 'Temperos / Condimentos', 'un', null, 80.0, (select id from fornecedores where lower(nome) = lower('Rei dos Temperos')), null, false),
  ('Nutella', 'Confeitaria / Sobremesas', 'un', null, 70.94, null, null, false),
  ('Ovo Branco Extra', 'Ovos / Derivados', 'un', null, 0.6667, (select id from fornecedores where lower(nome) = lower('Avícola Dalmas')), null, false),
  ('Pão de Hot Dog', 'Massas / Pães', 'un', null, 1.4, (select id from fornecedores where lower(nome) = lower('City pães')), null, false),
  ('Parmesão peça', 'Laticínios / Queijos', 'kg', null, 90.0, null, null, false),
  ('Pepino Japonês', 'Hortifruti', 'un', null, 6.66, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Pimenta Sriracha', 'Molhos / Condimentos', 'kg', null, null, (select id from fornecedores where lower(nome) = lower('Rei dos Temperos')), null, false),
  ('Pimentão', 'Hortifruti', 'kg', null, 11.9, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Pote de Papel Branco 550ML', 'Embalagens / Descartáveis', 'un', null, null, (select id from fornecedores where lower(nome) = lower('FC Cups')), null, false),
  ('Preparo em pó Ice Tea', 'Bebidas / Insumos', 'kg', null, null, (select id from fornecedores where lower(nome) = lower('Flavour House')), null, false),
  ('Purê de Batata', 'Preparos / Semiprontos', 'kg', null, null, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Salame', 'Embutidos / Frios', 'un', null, null, (select id from fornecedores where lower(nome) = lower('Di Calani')), null, false),
  ('Salsa Fresca (Cheiro verde)', 'Hortifruti', 'un', null, 33.0, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Salsa Trufada', 'Molhos / Condimentos', 'un', null, 194.39, (select id from fornecedores where lower(nome) = lower('Internet')), null, false),
  ('Salsão', 'Hortifruti', 'un', null, null, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Salsicha', 'Embutidos / Frios', 'un', null, 34.16, null, null, false),
  ('Shokupan', 'Massas / Pães', 'un', null, 0.51, (select id from fornecedores where lower(nome) = lower('Contato Henrique')), null, false),
  ('Sobrecoxa Desossada', 'Carnes / Proteínas', 'un', null, null, (select id from fornecedores where lower(nome) = lower('PMG')), null, false),
  ('Tomate Italiano', 'Hortifruti', 'un', null, 7.0, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Tomilho', 'Temperos / Condimentos', 'un', null, 48.0, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Tomilho fresco', 'Hortifruti', 'kg', null, null, (select id from fornecedores where lower(nome) = lower('Hortifruti')), null, false),
  ('Vinagrete', 'Preparos / Semiprontos', 'kg', null, null, null, 'Produção própria, sem ficha na planilha.', false),
  ('Xarope de Gengibre', 'Bebidas / Insumos', 'kg', null, null, null, 'Produção própria, sem ficha na planilha.', false),
  ('Zattar', 'Temperos / Condimentos', 'un', null, null, (select id from fornecedores where lower(nome) = lower('Rei dos Temperos')), null, false),
  ('Garrafinha', null, 'un', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false),
  ('Limonada', null, 'kg', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false),
  ('Xarope de Hibisco', null, 'kg', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false),
  ('Açúcar', null, 'un', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false),
  ('Limão', null, 'kg', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false),
  ('Pistache', null, 'kg', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false),
  ('Cheesecake Pistache', null, 'kg', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false),
  ('Sal', null, 'kg', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false),
  ('Mussarela pizza Monte Castelo', null, 'kg', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false),
  ('Bacon em cubos', null, 'kg', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false),
  ('Creme de Leite', null, 'kg', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false),
  ('Essência de Baunilha', null, 'kg', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false),
  ('Ovo', null, 'kg', null, null, null, 'Criado a partir das fichas da planilha; sem preço.', false);

insert into receitas (nome, tipo, linha, origem, unidade, preco_venda, ativo, versao_atual) values
  ('Água com gás', 'produto', 'Bebidas', 'revenda', 'un', 7.0, true, 1),
  ('Água sem gás', 'produto', 'Foca', 'propria', 'un', 7.0, true, 1),
  ('Coca-Cola', 'produto', 'Bebidas', 'revenda', 'un', 9.0, true, 1),
  ('Coca-Zero', 'produto', 'Bebidas', 'revenda', 'un', 9.0, true, 1),
  ('Coleslaw', 'preparo', 'Foca', 'propria', 'kg', null, true, 1),
  ('Crema de Queijo', 'preparo', 'Foca', 'propria', 'kg', null, true, 1),
  ('Foca na Mortadela', 'produto', 'Foca', 'propria', 'un', 50.0, true, 1),
  ('Foca na Trufa', 'produto', 'Foca', 'propria', 'un', 50.0, true, 1),
  ('Foca no Parma', 'produto', 'Foca', 'propria', 'un', 55.0, true, 1),
  ('Foca no Pastrami', 'produto', 'Foca', 'propria', 'un', 55.0, true, 1),
  ('Guaraná', 'produto', 'Bebidas', 'revenda', 'un', 9.0, true, 1),
  ('Guaraná Zero', 'produto', 'Bebidas', 'revenda', 'un', 9.0, true, 1),
  ('Maionese Base', 'preparo', 'Pizza', 'propria', 'kg', null, true, 1),
  ('Massa de pizza', 'preparo', 'Pizza', 'propria', 'un', null, true, 1),
  ('Mistura Ovo Carbonara', 'preparo', 'Romana', 'propria', 'un', null, false, 1),
  ('Mix de Cogumelos', 'preparo', 'Foca', 'propria', 'un', null, true, 1),
  ('Pesto de manjericão', 'preparo', 'Pizza', 'propria', 'kg', null, true, 1),
  ('Pizza Castelões', 'produto', 'Pizza', 'propria', 'un', 50.0, true, 1),
  ('Pizza Frango Catupiry', 'produto', 'Pizza', 'propria', 'un', 55.0, true, 1),
  ('Pizza Marguerita Especial', 'produto', 'Pizza', 'propria', 'un', 50.0, true, 1),
  ('Pizza Trufada', 'produto', 'Pizza', 'propria', 'un', 55.0, true, 1),
  ('Porção Batata', 'produto', 'Foca', 'propria', 'un', 10.0, true, 1),
  ('Romana de Calabresa', 'produto', 'Romana', 'propria', 'un', 30.0, false, 1),
  ('Romana de Carbonara', 'produto', 'Romana', 'propria', 'un', 30.0, false, 1),
  ('Romana de Copa ao Pesto', 'produto', 'Romana', 'propria', 'un', 30.0, false, 1),
  ('Romana de Marguerita', 'produto', 'Romana', 'propria', 'un', 27.5, false, 1),
  ('Romana de Quatro Formaggi', 'produto', 'Romana', 'propria', 'un', 30.0, false, 1),
  ('Romana de Smores', 'produto', 'Romana', 'propria', 'un', 30.0, false, 1),
  ('Base Amenteigada de Cheesecake', 'preparo', 'Foca', 'propria', 'un', null, false, 1),
  ('Blood Lemonade', 'produto', 'Bebidas', 'propria', 'un', 12.0, false, 1),
  ('Calda de Frutas vermelhas caseira', 'preparo', 'Foca', 'propria', 'kg', null, false, 1),
  ('Chá Gelado Gengibre', 'produto', 'Bebidas', 'propria', 'un', 12.0, false, 1),
  ('Cheesecake De Pistache', 'preparo', 'Foca', 'propria', 'un', null, false, 1),
  ('Fatia Cheesecake Pistache', 'produto', 'Foca', 'propria', 'un', null, false, 1),
  ('Fettuccine Formaggio', 'produto', 'Massa', 'propria', 'un', 45.0, false, 1),
  ('Fettuccine Pomodoro', 'produto', 'Massa', 'propria', 'un', 45.0, false, 1),
  ('Fettuccine Trufado', 'produto', 'Massa', 'propria', 'un', 55.0, false, 1),
  ('Foca Na Carne Louca', 'produto', 'Foca', 'propria', 'un', 45.0, false, 1),
  ('Foca Na Carne Louca', 'preparo', 'Foca', 'propria', 'kg', null, false, 1),
  ('Foca no Árabe', 'produto', 'Foca', 'propria', 'un', 45.0, false, 1),
  ('Foca No Parmegiana', 'produto', 'Foca', 'propria', 'un', 70.0, false, 1),
  ('Foca No Verdi', 'produto', 'Foca', 'propria', 'un', 35.0, false, 1),
  ('Frango Empanado', 'preparo', 'Foca', 'propria', 'un', null, false, 1),
  ('Hot Dog Completo', 'produto', 'Dog', 'propria', 'un', 35.0, false, 1),
  ('Hot Dog Simples', 'produto', 'Dog', 'propria', 'un', 25.0, false, 1),
  ('Massa de Cheesecake', 'preparo', 'Foca', 'propria', 'un', null, false, 1),
  ('Molho Árabe', 'preparo', 'Foca', 'propria', 'un', null, false, 1),
  ('Molho Branco', 'preparo', 'Massa', 'propria', 'un', null, false, 1),
  ('Molho Pomodoro', 'preparo', 'Massa', 'propria', 'un', null, false, 1),
  ('Panuozzo Parma', 'produto', 'Pizza', 'propria', 'un', 65.0, false, 1),
  ('Pizza Burrata', 'produto', 'Pizza', 'propria', 'un', 55.0, false, 1),
  ('Pizza Nutella Com Morango', 'produto', 'Pizza', 'propria', 'un', 50.0, false, 1),
  ('Pizza Pistache', 'produto', 'Pizza', 'propria', 'un', 55.0, false, 1),
  ('Pizza Presunto Parma', 'produto', 'Pizza', 'propria', 'un', 55.0, false, 1),
  ('Polpettone', 'preparo', 'Massa', 'propria', 'un', null, false, 1),
  ('Prato de pizza', 'preparo', 'Massa', 'propria', 'kg', null, false, 1),
  ('Pesto de rúcula', 'preparo', 'Foca', 'propria', 'kg', null, true, 1);

insert into receita_versoes (receita_id, numero, rendimento, custo_total, nota) values
  ((select id from receitas where lower(nome) = 'água com gás' and tipo = 'produto'), 1, 1, 1.5, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'água sem gás' and tipo = 'produto'), 1, 1, 1.5, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'coca-cola' and tipo = 'produto'), 1, 1, 3.39, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'coca-zero' and tipo = 'produto'), 1, 1, 3.39, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'coleslaw' and tipo = 'preparo'), 1, 1, 11.9779, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'crema de queijo' and tipo = 'preparo'), 1, 1, 30.7992, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'foca na mortadela' and tipo = 'produto'), 1, 1, 8.1211, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'foca na trufa' and tipo = 'produto'), 1, 1, 12.7032, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'foca no parma' and tipo = 'produto'), 1, 1, 14.1582, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'foca no pastrami' and tipo = 'produto'), 1, 1, 13.8135, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'guaraná' and tipo = 'produto'), 1, 1, 2.99, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'guaraná zero' and tipo = 'produto'), 1, 1, 2.8912, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'maionese base' and tipo = 'preparo'), 1, 1, 11.3064, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'massa de pizza' and tipo = 'preparo'), 1, 1, 1.6152, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'mistura ovo carbonara' and tipo = 'preparo'), 1, 1, 48.1265, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'mix de cogumelos' and tipo = 'preparo'), 1, 1, 69.7754, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'pesto de manjericão' and tipo = 'preparo'), 1, 1, 46.3975, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'pizza castelões' and tipo = 'produto'), 1, 1, 8.7589, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'pizza frango catupiry' and tipo = 'produto'), 1, 1, 6.259, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'pizza marguerita especial' and tipo = 'produto'), 1, 1, 6.708, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'pizza trufada' and tipo = 'produto'), 1, 1, 11.9384, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'porção batata' and tipo = 'produto'), 1, 1, 1.295, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'romana de calabresa' and tipo = 'produto'), 1, 1, 5.0173, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'romana de carbonara' and tipo = 'produto'), 1, 1, 6.5687, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'romana de copa ao pesto' and tipo = 'produto'), 1, 1, 6.0439, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'romana de marguerita' and tipo = 'produto'), 1, 1, 4.2903, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'romana de quatro formaggi' and tipo = 'produto'), 1, 1, 5.0164, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'romana de smores' and tipo = 'produto'), 1, 1, 7.1194, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'base amenteigada de cheesecake' and tipo = 'preparo'), 1, 1, 4.1833, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'blood lemonade' and tipo = 'produto'), 1, 1, 0.0, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'calda de frutas vermelhas caseira' and tipo = 'preparo'), 1, 1, 41.2653, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'chá gelado gengibre' and tipo = 'produto'), 1, 1, 0.0, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'cheesecake de pistache' and tipo = 'preparo'), 1, 1, 87.0039, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'fatia cheesecake pistache' and tipo = 'produto'), 1, 1, 0.0, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'fettuccine formaggio' and tipo = 'produto'), 1, 1, 4.6907, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'fettuccine pomodoro' and tipo = 'produto'), 1, 1, 4.9479, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'fettuccine trufado' and tipo = 'produto'), 1, 1, 6.1351, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'foca na carne louca' and tipo = 'produto'), 1, 1, 5.2589, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'foca na carne louca' and tipo = 'preparo'), 1, 1, 26.0028, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'foca no árabe' and tipo = 'produto'), 1, 1, 11.5831, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'foca no parmegiana' and tipo = 'produto'), 1, 1, 7.5846, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'foca no verdi' and tipo = 'produto'), 1, 1, 8.9135, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'frango empanado' and tipo = 'preparo'), 1, 1, 2.2127, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'hot dog completo' and tipo = 'produto'), 1, 1, 8.9478, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'hot dog simples' and tipo = 'produto'), 1, 1, 4.816, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'massa de cheesecake' and tipo = 'preparo'), 1, 1, 14.729, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'molho árabe' and tipo = 'preparo'), 1, 1, 8.6808, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'molho branco' and tipo = 'preparo'), 1, 1, 9.9072, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'molho pomodoro' and tipo = 'preparo'), 1, 1, 15.2396, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'panuozzo parma' and tipo = 'produto'), 1, 1, 20.183, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'pizza burrata' and tipo = 'produto'), 1, 1, 6.6705, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'pizza nutella com morango' and tipo = 'produto'), 1, 1, 7.7295, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'pizza pistache' and tipo = 'produto'), 1, 1, 17.8745, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'pizza presunto parma' and tipo = 'produto'), 1, 1, 6.6624, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'polpettone' and tipo = 'preparo'), 1, 1, 5.5313, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'prato de pizza' and tipo = 'preparo'), 1, 1, 0.0808, 'Importada da planilha DPEN 25-26 em 08/10/2026.'),
  ((select id from receitas where lower(nome) = 'pesto de rúcula' and tipo = 'preparo'), 1, 1, 44.7075, 'Importada da planilha DPEN 25-26 em 08/10/2026.');

insert into receita_itens (versao_id, ordem, insumo_id, sub_receita_id, quantidade, aproveitamento) values
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'água com gás' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'água com gás'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'água sem gás' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'água'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'coca-cola' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'coca-cola'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'coca-zero' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'coca-zero'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'coleslaw' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'mostarda galão cepera 3.3kg'), null, 0.01, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'coleslaw' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'cenoura'), null, 0.15, 0.85),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'coleslaw' and r.tipo = 'preparo' and v.numero = 1), 3, null, (select id from receitas where lower(nome) = 'maionese base' and tipo = 'preparo'), 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'coleslaw' and r.tipo = 'preparo' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'repolho roxo'), null, 0.25, 0.88),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'coleslaw' and r.tipo = 'preparo' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'repolho verde'), null, 0.5, 0.9),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'crema de queijo' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'creme de leite 0.2ml'), null, 0.333, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'crema de queijo' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'queijo minas'), null, 0.666, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na mortadela' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'limão tahiti'), null, 0.04, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na mortadela' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'pistache sem casca cru'), null, 0.003, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na mortadela' and r.tipo = 'produto' and v.numero = 1), 3, null, (select id from receitas where lower(nome) = 'crema de queijo' and tipo = 'preparo'), 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na mortadela' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'mortadela'), null, 0.11, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na mortadela' and r.tipo = 'produto' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.167, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na trufa' and r.tipo = 'produto' and v.numero = 1), 1, null, (select id from receitas where lower(nome) = 'mix de cogumelos' and tipo = 'preparo'), 0.08, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na trufa' and r.tipo = 'produto' and v.numero = 1), 2, null, (select id from receitas where lower(nome) = 'pesto de rúcula' and tipo = 'preparo'), 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na trufa' and r.tipo = 'produto' and v.numero = 1), 3, null, (select id from receitas where lower(nome) = 'crema de queijo' and tipo = 'preparo'), 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na trufa' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.167, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no parma' and r.tipo = 'produto' and v.numero = 1), 1, null, (select id from receitas where lower(nome) = 'pesto de rúcula' and tipo = 'preparo'), 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no parma' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.018, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no parma' and r.tipo = 'produto' and v.numero = 1), 3, null, (select id from receitas where lower(nome) = 'crema de queijo' and tipo = 'preparo'), 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no parma' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'presunto parma 80g'), null, 0.015, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no parma' and r.tipo = 'produto' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'copa lombo'), null, 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no parma' and r.tipo = 'produto' and v.numero = 1), 6, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.167, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no pastrami' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'picles burgers'), null, 0.011, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no pastrami' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'mostarda anciene'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no pastrami' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'mussarela'), null, 0.02, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no pastrami' and r.tipo = 'produto' and v.numero = 1), 4, null, (select id from receitas where lower(nome) = 'coleslaw' and tipo = 'preparo'), 0.06, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no pastrami' and r.tipo = 'produto' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.167, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no pastrami' and r.tipo = 'produto' and v.numero = 1), 6, (select id from insumos where lower(nome) = 'pastrami'), null, 0.085, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'guaraná' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'guaraná'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'guaraná zero' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'guaraná zero'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'maionese base' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'mostarda galão cepera 3.3kg'), null, 0.105, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'maionese base' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'gema pasteurizada'), null, 0.089, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'maionese base' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'óleo de soja'), null, 0.85, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'massa de pizza' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'sal refinado'), null, 0.002, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'massa de pizza' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'fermento biológico'), null, 0.002, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'massa de pizza' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'óleo de soja'), null, 0.003, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'massa de pizza' and r.tipo = 'preparo' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'farinha de trigo italiana'), null, 0.125, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'mistura ovo carbonara' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'gema pasteurizada'), null, 0.26, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'mistura ovo carbonara' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'parmesão ralado pacote'), null, 0.21, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'mistura ovo carbonara' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'catupiry'), null, 0.526, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'mix de cogumelos' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'missô'), null, 0.075, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'mix de cogumelos' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'manteiga sem sal'), null, 0.075, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'mix de cogumelos' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'cogumelo paris'), null, 0.45, 0.92),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'mix de cogumelos' and r.tipo = 'preparo' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'shimeji'), null, 0.75, 0.9),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'mix de cogumelos' and r.tipo = 'preparo' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'salsa trufada'), null, 0.18, 0.9),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pesto de manjericão' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'manjericão'), null, 0.4, 0.55),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pesto de manjericão' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'xerem de castanha de caju'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pesto de manjericão' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'parmesão ralado pacote'), null, 0.15, 0.96),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pesto de manjericão' and r.tipo = 'preparo' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'azeite'), null, 0.4, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza castelões' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza castelões' and r.tipo = 'produto' and v.numero = 1), 2, null, (select id from receitas where lower(nome) = 'massa de pizza' and tipo = 'preparo'), 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza castelões' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'mussarela'), null, 0.08, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza castelões' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'calabresa fatiada pizza'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza frango catupiry' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'peito de frango'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza frango catupiry' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza frango catupiry' and r.tipo = 'produto' and v.numero = 1), 3, null, (select id from receitas where lower(nome) = 'massa de pizza' and tipo = 'preparo'), 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza frango catupiry' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'catupiry'), null, 0.08, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza marguerita especial' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'manjericão'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza marguerita especial' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza marguerita especial' and r.tipo = 'produto' and v.numero = 1), 3, null, (select id from receitas where lower(nome) = 'massa de pizza' and tipo = 'preparo'), 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza marguerita especial' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'mussarela de bufala'), null, 0.07, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza trufada' and r.tipo = 'produto' and v.numero = 1), 1, null, (select id from receitas where lower(nome) = 'mix de cogumelos' and tipo = 'preparo'), 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza trufada' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza trufada' and r.tipo = 'produto' and v.numero = 1), 3, null, (select id from receitas where lower(nome) = 'massa de pizza' and tipo = 'preparo'), 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza trufada' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'mussarela'), null, 0.08, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'porção batata' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'cestinha focaccia evento'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'porção batata' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'pety fritas'), null, 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de calabresa' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'cebola roxa'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de calabresa' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de calabresa' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'calabresa fatiada pizza'), null, 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de calabresa' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'catupiry'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de calabresa' and r.tipo = 'produto' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.0833, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de carbonara' and r.tipo = 'produto' and v.numero = 1), 1, null, (select id from receitas where lower(nome) = 'mistura ovo carbonara' and tipo = 'preparo'), 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de carbonara' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'pimenta do reino'), null, 0.001, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de carbonara' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'bacon'), null, 0.015, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de carbonara' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'mussarela'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de carbonara' and r.tipo = 'produto' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.0833, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de copa ao pesto' and r.tipo = 'produto' and v.numero = 1), 1, null, (select id from receitas where lower(nome) = 'pesto de manjericão' and tipo = 'preparo'), 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de copa ao pesto' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de copa ao pesto' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'redução de balsâmico'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de copa ao pesto' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'copa lombo'), null, 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de copa ao pesto' and r.tipo = 'produto' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.0833, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de marguerita' and r.tipo = 'produto' and v.numero = 1), 1, null, (select id from receitas where lower(nome) = 'pesto de manjericão' and tipo = 'preparo'), 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de marguerita' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de marguerita' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'mussarela'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de marguerita' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.0833, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de quatro formaggi' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de quatro formaggi' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'parmesão ralado pacote'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de quatro formaggi' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'gorgonzola'), null, 0.015, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de quatro formaggi' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'catupiry'), null, 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de quatro formaggi' and r.tipo = 'produto' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.0833, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de smores' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'marshmallow'), null, 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de smores' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.0833, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'romana de smores' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'creme de ovomaltine 900g'), null, 0.06, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'base amenteigada de cheesecake' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'bolacha maizena'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'base amenteigada de cheesecake' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'manteiga sem sal'), null, 0.06, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'blood lemonade' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'garrafinha'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'blood lemonade' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'limonada'), null, 0.022, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'blood lemonade' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'xarope de hibisco'), null, 0.111, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'calda de frutas vermelhas caseira' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'açúcar'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'calda de frutas vermelhas caseira' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'frutas vermelhas congeladas'), null, 1.0, 0.98),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'calda de frutas vermelhas caseira' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'limão'), null, 0.125, 0.9),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'chá gelado gengibre' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'garrafinha'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'chá gelado gengibre' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'preparo em pó ice tea'), null, 0.003, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'chá gelado gengibre' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'xarope de gengibre'), null, 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'cheesecake de pistache' and r.tipo = 'preparo' and v.numero = 1), 1, null, (select id from receitas where lower(nome) = 'base amenteigada de cheesecake' and tipo = 'preparo'), 0.15, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'cheesecake de pistache' and r.tipo = 'preparo' and v.numero = 1), 2, null, (select id from receitas where lower(nome) = 'calda de frutas vermelhas caseira' and tipo = 'preparo'), 0.25, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'cheesecake de pistache' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'ganache de pistache'), null, 0.18, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'cheesecake de pistache' and r.tipo = 'preparo' and v.numero = 1), 4, null, (select id from receitas where lower(nome) = 'massa de cheesecake' and tipo = 'preparo'), 1.125, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'cheesecake de pistache' and r.tipo = 'preparo' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'pistache'), null, 0.02, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fatia cheesecake pistache' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'cheesecake pistache'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fettuccine formaggio' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'fettuccine'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fettuccine formaggio' and r.tipo = 'produto' and v.numero = 1), 2, null, (select id from receitas where lower(nome) = 'molho branco' and tipo = 'preparo'), 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fettuccine formaggio' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'parmesão peça'), null, 0.02, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fettuccine formaggio' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'parmesão ralado pacote'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fettuccine pomodoro' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'fettuccine'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fettuccine pomodoro' and r.tipo = 'produto' and v.numero = 1), 2, null, (select id from receitas where lower(nome) = 'molho pomodoro' and tipo = 'preparo'), 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fettuccine pomodoro' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'parmesão ralado pacote'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fettuccine trufado' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'fettuccine'), null, 0.08, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fettuccine trufado' and r.tipo = 'produto' and v.numero = 1), 2, null, (select id from receitas where lower(nome) = 'mix de cogumelos' and tipo = 'preparo'), 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fettuccine trufado' and r.tipo = 'produto' and v.numero = 1), 3, null, (select id from receitas where lower(nome) = 'molho branco' and tipo = 'preparo'), 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fettuccine trufado' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'parmesão peça'), null, 0.02, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'fettuccine trufado' and r.tipo = 'produto' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'parmesão ralado pacote'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na carne louca' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'carne louca'), null, 0.08, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na carne louca' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.167, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na carne louca' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'milho verde'), null, 0.015, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na carne louca' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'vinagrete'), null, 0.02, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na carne louca' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'carne de lagarto'), null, 0.6, 0.8),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na carne louca' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'cebola'), null, 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na carne louca' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'pimenta sriracha'), null, 0.015, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na carne louca' and r.tipo = 'preparo' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'pimentão'), null, 0.07, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na carne louca' and r.tipo = 'preparo' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'sal'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na carne louca' and r.tipo = 'preparo' and v.numero = 1), 6, (select id from insumos where lower(nome) = 'salsão'), null, 0.04, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca na carne louca' and r.tipo = 'preparo' and v.numero = 1), 7, (select id from insumos where lower(nome) = 'tomilho'), null, 0.001, 0.9),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no árabe' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'cebola roxa'), null, 0.01, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no árabe' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.167, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no árabe' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'kafta de cordeiro'), null, 0.07, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no árabe' and r.tipo = 'produto' and v.numero = 1), 4, null, (select id from receitas where lower(nome) = 'molho árabe' and tipo = 'preparo'), 0.024, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no árabe' and r.tipo = 'produto' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'pepino japonês'), null, 0.026, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no árabe' and r.tipo = 'produto' and v.numero = 1), 6, (select id from insumos where lower(nome) = 'pety fritas'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no árabe' and r.tipo = 'produto' and v.numero = 1), 7, (select id from insumos where lower(nome) = 'tomate italiano'), null, 0.035, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no árabe' and r.tipo = 'produto' and v.numero = 1), 8, (select id from insumos where lower(nome) = 'zattar'), null, 0.003, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no parmegiana' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.167, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no parmegiana' and r.tipo = 'produto' and v.numero = 1), 2, null, (select id from receitas where lower(nome) = 'frango empanado' and tipo = 'preparo'), 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no parmegiana' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no parmegiana' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'mussarela pizza monte castelo'), null, 0.02, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no verdi' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'abobrinha grelhada'), null, 0.15, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no verdi' and r.tipo = 'produto' and v.numero = 1), 2, null, (select id from receitas where lower(nome) = 'crema de queijo' and tipo = 'preparo'), 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no verdi' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'focaccia forma'), null, 0.167, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no verdi' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.018, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no verdi' and r.tipo = 'produto' and v.numero = 1), 5, null, (select id from receitas where lower(nome) = 'pesto de manjericão' and tipo = 'preparo'), 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'foca no verdi' and r.tipo = 'produto' and v.numero = 1), 6, (select id from insumos where lower(nome) = 'pety fritas'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'frango empanado' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'farinha de trigo'), null, 0.01, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'frango empanado' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'farinha panko'), null, 0.015, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'frango empanado' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'ovo branco extra'), null, 0.012, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'frango empanado' and r.tipo = 'preparo' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'peito de frango'), null, 0.1, 0.8),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'hot dog completo' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'bacon em cubos'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'hot dog completo' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'batata palha'), null, 0.015, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'hot dog completo' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'milho verde'), null, 0.015, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'hot dog completo' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'pão de hot dog'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'hot dog completo' and r.tipo = 'produto' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'purê de batata'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'hot dog completo' and r.tipo = 'produto' and v.numero = 1), 6, (select id from insumos where lower(nome) = 'salsicha'), null, 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'hot dog simples' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'pão de hot dog'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'hot dog simples' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'purê de batata'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'hot dog simples' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'salsicha'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'massa de cheesecake' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'açúcar'), null, 0.13, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'massa de cheesecake' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'cream cheese'), null, 0.65, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'massa de cheesecake' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'creme de leite'), null, 0.16, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'massa de cheesecake' and r.tipo = 'preparo' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'essência de baunilha'), null, 0.002, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'massa de cheesecake' and r.tipo = 'preparo' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'limão'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'massa de cheesecake' and r.tipo = 'preparo' and v.numero = 1), 6, (select id from insumos where lower(nome) = 'ovo'), null, 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho árabe' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'alho em pó'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho árabe' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'iogurte'), null, 0.815, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho árabe' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'molho de tahine apimentado'), null, 0.163, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho árabe' and r.tipo = 'preparo' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'pimenta do reino'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho árabe' and r.tipo = 'preparo' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'sal'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho árabe' and r.tipo = 'preparo' and v.numero = 1), 6, (select id from insumos where lower(nome) = 'zattar'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho branco' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'cebola'), null, 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho branco' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'farinha de trigo'), null, 0.06, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho branco' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'leite integral'), null, 0.86, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho branco' and r.tipo = 'preparo' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'manteiga sem sal'), null, 0.06, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho branco' and r.tipo = 'preparo' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'noz moscada'), null, 0.001, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho branco' and r.tipo = 'preparo' and v.numero = 1), 6, (select id from insumos where lower(nome) = 'sal refinado'), null, 0.01, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho pomodoro' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'alho'), null, 0.02, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho pomodoro' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'azeite'), null, 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho pomodoro' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'cebola'), null, 0.12, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho pomodoro' and r.tipo = 'preparo' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'cenoura'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho pomodoro' and r.tipo = 'preparo' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'sal refinado'), null, 0.001, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'molho pomodoro' and r.tipo = 'preparo' and v.numero = 1), 6, (select id from insumos where lower(nome) = 'tomate italiano'), null, 1.5, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'panuozzo parma' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'copa lombo'), null, 0.13, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'panuozzo parma' and r.tipo = 'produto' and v.numero = 1), 2, null, (select id from receitas where lower(nome) = 'massa de pizza' and tipo = 'preparo'), 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'panuozzo parma' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'mussarela de bufala'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'panuozzo parma' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'presunto parma 80g'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'panuozzo parma' and r.tipo = 'produto' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'redução de balsâmico'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'panuozzo parma' and r.tipo = 'produto' and v.numero = 1), 6, (select id from insumos where lower(nome) = 'rúcula'), null, 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza burrata' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'burrata'), null, 1.0, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza burrata' and r.tipo = 'produto' and v.numero = 1), 2, null, (select id from receitas where lower(nome) = 'massa de pizza' and tipo = 'preparo'), 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza burrata' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza burrata' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'mussarela de bufala'), null, 0.07, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza nutella com morango' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'creme de leite'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza nutella com morango' and r.tipo = 'produto' and v.numero = 1), 2, null, (select id from receitas where lower(nome) = 'massa de pizza' and tipo = 'preparo'), 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza nutella com morango' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'morango'), null, 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza nutella com morango' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'nutella'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza pistache' and r.tipo = 'produto' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'creme de leite 0.2ml'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza pistache' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'ganache de pistache'), null, 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza pistache' and r.tipo = 'produto' and v.numero = 1), 3, null, (select id from receitas where lower(nome) = 'massa de pizza' and tipo = 'preparo'), 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza pistache' and r.tipo = 'produto' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'pistache sem casca cru'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza presunto parma' and r.tipo = 'produto' and v.numero = 1), 1, null, (select id from receitas where lower(nome) = 'massa de pizza' and tipo = 'preparo'), 0.2, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza presunto parma' and r.tipo = 'produto' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'molho tomate italiano lata 2.55kg'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza presunto parma' and r.tipo = 'produto' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'mussarela pizza monte castelo'), null, 0.08, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza presunto parma' and r.tipo = 'produto' and v.numero = 1), 4, null, (select id from receitas where lower(nome) = 'pesto de manjericão' and tipo = 'preparo'), 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pizza presunto parma' and r.tipo = 'produto' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'presunto parma 80g'), null, 0.025, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'polpettone' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'alho frito'), null, 0.02, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'polpettone' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'blend burger 1 unidade (100g)'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'polpettone' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'farinha de trigo'), null, 0.03, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'polpettone' and r.tipo = 'preparo' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'farinha panko'), null, 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'polpettone' and r.tipo = 'preparo' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'leite integral'), null, 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'polpettone' and r.tipo = 'preparo' and v.numero = 1), 6, (select id from insumos where lower(nome) = 'ovo branco extra'), null, 0.066, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'polpettone' and r.tipo = 'preparo' and v.numero = 1), 7, (select id from insumos where lower(nome) = 'sal refinado'), null, 0.02, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'polpettone' and r.tipo = 'preparo' and v.numero = 1), 8, (select id from insumos where lower(nome) = 'salsa fresca (cheiro verde)'), null, 0.005, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'prato de pizza' and r.tipo = 'preparo' and v.numero = 1), 1, null, (select id from receitas where lower(nome) = 'massa de pizza' and tipo = 'preparo'), 0.05, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pesto de rúcula' and r.tipo = 'preparo' and v.numero = 1), 1, (select id from insumos where lower(nome) = 'rúcula'), null, 0.335, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pesto de rúcula' and r.tipo = 'preparo' and v.numero = 1), 2, (select id from insumos where lower(nome) = 'xerem de castanha de caju'), null, 0.1, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pesto de rúcula' and r.tipo = 'preparo' and v.numero = 1), 3, (select id from insumos where lower(nome) = 'azeite'), null, 0.465, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pesto de rúcula' and r.tipo = 'preparo' and v.numero = 1), 4, (select id from insumos where lower(nome) = 'alho'), null, 0.017, 1.0),
  ((select v.id from receita_versoes v join receitas r on r.id = v.receita_id where lower(r.nome) = 'pesto de rúcula' and r.tipo = 'preparo' and v.numero = 1), 5, (select id from insumos where lower(nome) = 'parmesão ralado pacote'), null, 0.12, 1.0);
